openai:
  embedding_model: "text-embedding-3-small"
  model: "gpt-4o-mini"

ollama:
  host: "http://localhost:11434"
  embedding_model: "nomic-embed-text"
  model: "huihui_ai/smallthinker-abliterated:3b-q8_0"
  num_ctx: 32000

backend:
  llm_backend: "openai"
  port: 8000
